---
image: python:3.10

services:
  - neo4j:3.5

stages:
  - test
  - deploy

before_script:
  - python -V

test:
  tags:
    - docker
  script:
    - python setup.py testing
    - python setup.py test

deploy:
  only:
    - master
    - tags
  script:
    - pip install -U twine build
    - python -m build
      #    - twine upload --repository testpypi dist/* --verbose
