---
stages:
  - test
  - deploy

image: python:3

services:
  - neo4j:3.5


before_script:
  - python -V

test:
  stage: test
  tags:
    - docker
  script:
    - python setup.py testing
    - python setup.py test

deploy:
  stage: deploy
  only:
    - tags
  script:
    - pip install -U twine build
    - python -m build
    - twine upload dist/* --verbose
